version: '2'
services:
  nginx:
    build:
      context: ./nginx-phpfpm
    image: nginx_image1
    volumes:
      - /var/log/nginx/access.log:/var/log/nginx/access.log
    ports:
      - "80:80"
  pytail:
    build:
      context: ./pytail
    image: pytail_image1
    volumes:
      - /var/log/stats.log:/var/log/stats.log
      - /var/log/nginx/access.log:/var/log/nginx/access.log
    stdin_open: true
    tty: true
  pygen:
    build:
      context: ./pygen
    image: pygen_image1
    stdin_open: true
    tty: true

