version: '2'
services:
  nginx:
    build:
      context: ./nginx-phpfpm
    image: nginx_image1
    volumes:
      - /var/log:/var/log
      - /var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
  pytail:
    build:
      context: ./pytail
    image: pytail_image1
    volumes_from:
      - "nginx"
    stdin_open: true
    tty: true
    depends_on:
      - "nginx"
  pygen:
    build:
      context: ./pygen
    image: pygen_image1
    stdin_open: true
    tty: true
    depends_on:
      - "pytail"
